server:
  port: 9001
dubbo:
  scan:
    basePackages: com.jt  #指定包路径
  application:
    name: consumer-user   #业务标识 自己定义的
  registry:
    address: zookeeper://192.168.126.174:2181?backup=192.168.126.174:2182,192.168.126.174:2183