#语法: 1.K-V结构   使用":"号进行链接.
#      2.有层级关系 注意缩进(空格or tab键)
#      3.添加value时 注意空格.
#选中默认的环境
spring:
  profiles:
    active: dev
--- 
#环境1  定义环境名称 dev
spring:
  profiles: dev
  
server:
  port: 8090   #指定端口号信息

#指定项目发布路径 tomcat 发布到哪个目录下?发布到webapp目录下的/ROOT中
  servlet:
    context-path: /   #发布默认路径

#实现属性赋值操作  jdbc.driver
jdbc:
  driver: mysqlDriver
  name:   mysql

#环境分割
---
#环境2 prod
spring:
  profiles: prod
server:
  port: 8095   #指定端口号信息

#指定项目发布路径 tomcat 发布到哪个目录下?发布到webapp目录下的/ROOT中
  servlet:
    context-path: /   #发布默认路径
#实现属性赋值操作  jdbc.driver
jdbc:
  driver: mysqlDriver
  name:   mysql